name: Auto Assign PR Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Assign Reviewers
        uses: kentaro-m/auto-assign-action@v2
        with:
          addReviewers: true
          addAssignees: false
          reviewers: |
            - affanshaikhsurab
          skipKeywords: |
            - wip
          numberOfReviewers: 1
